//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LvSample.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_LVSAMPLE_DIALOG             102
#define IDD_DIALOG_ZDRIVE_RANGE         103
#define IDD_DIALOG_INFO                 104
#define IDB_BITMAP_D                    129
#define IDB_BITMAP_DD                   130
#define IDB_BITMAP_LED_OFF              131
#define IDB_BITMAP_LED_ON               132
#define IDB_BITMAP_U                    133
#define IDB_BITMAP_UU                   134
#define IDR_MENU1                       135
#define IDD_DIALOG_SOFTLIMIT            136
#define IDD_DIALOG_COMPENSATION         137
#define IDD_DIALOG_CONTROL              138
#define IDD_DIALOG_USEROBSERVATION      139
#define IDD_DIALOG_SETUP                140
#define IDD_DIALOG_COMMAND              141
#define IDD_DIALOG_DEVICE               142
#define IDD_DIALOG_AF_OFFSET            143
#define IDI_ICON_LVCONTROL              146
#define IDD_DIALOG_ABOUT                147
#define IDB_BITMAP_LV_ABOUT             148
#define IDS_SPEED_HIGH                  149
#define IDS_SPEED_MIDDLE                150
#define IDS_SPEED_LOW                   151
#define IDS_INTERLOCK_DEFAULT           152
#define IDS_INTERLOCK_OPTIONAL          153
#define IDS_LIMIT_UPPER                 154
#define IDS_LIMIT_LOWER                 155
#define IDS_MESSAGE_INPUT_COMMAND       156
#define IDS_MESSAGE_NOT_SUPPORTED       157
#define IDS_MESSAGE_INVALID_COMMAND     158
#define IDS_MESSAGE_OUT_OF_RANGE        159
#define IDS_MESSAGE_AF_OFFSET_CHANGED   160
#define IDS_MESSAGE_INVALID_FORMAT      161
#define IDS_MESSAGE_INPUT_AF_OFFSET     162
#define IDS_MESSAGE_COMPULSORILY_ROTATED 163
#define IDS_MESSAGE_ROTATION_FAILED     164
#define IDS_ZDRIVE_ESCAPE               165
#define IDS_ZDRIVE_REFOCUS              166
#define IDS_MESSAGE_CANNOT_CHANGE_DIC   167
#define IDS_MESSAGE_SHUTTER_FAILED      168
#define IDS_MESSAGE_SHUTTER_SHORT       169
#define IDS_MESSAGE_SHUTTER_INPUT       170
#define IDS_MESSAGE_NOT_ESCAPE          171
#define IDS_MESSAGE_ESCAPING_ZDRIVE     172
#define IDS_MESSAGE_NO_RESPONSE_FROM_DEVICE 173
#define IDS_MESSAGE_USER_OFFSET_INITIALIZED 174
#define IDS_MESSAGE_COMPULSORILY_ROTATED_SAFETY_LOCK 175
#define IDS_MESSAGE_SAFETY_LOCK         176
#define IDS_MESSAGE_SELECT_DEVICE       177
#define IDS_MESSAGE_NOT_CONNECTED_DEVICE 178
#define IDS_STRING_INFODLG_DELIMITER    179
#define IDS_MESSAGE_RANGE_BOUND         180
#define IDS_MESSAGE_RANGE_CURRENT       181
#define IDS_MESSAGE_RANGE_OUTSIDE       182
#define IDS_MESSAGE_RANGE1              183
#define IDS_MESSAGE_RANGE2              184
#define IDS_MESSAGE_RANGE3              185
#define IDS_MESSAGE_RANGE_INPUT_VALUE   186
#define IDS_MESSAGE_CONNECT_DEVICE_FAILED 187
#define IDS_NAME_HELP                   188
#define IDC_COMBO_OBSERVATION_MODE      1000
#define IDC_STATIC_FRM_EPI              1001
#define IDC_COMBO_OPTIONAL_MODE         1001
#define IDC_STATIC_FRM_FIBER            1002
#define IDC_STATIC_FRM_NOSEPIECE        1003
#define IDC_STATIC_FRM_CUBE             1004
#define IDC_STATIC_FRM_SWITCH           1004
#define IDC_STATIC_FRM_DIA              1005
#define IDC_STATIC_FRM_BUZZER           1005
#define IDC_STATIC_FRM_ZDRIVE           1006
#define IDC_STATIC_FRM_APERTURE         1007
#define IDC_STATIC_FRM_OBJECTIVE        1007
#define IDC_STATIC_FRM_DIC              1008
#define IDC_STATIC_FRM_INTERLOCK        1009
#define IDC_STATIC_OBSERVATION_MODE     1010
#define IDC_BUTTON_EPI_LAMP             1011
#define IDC_STATIC_USER_MODE            1011
#define IDC_BUTTON_FIBER                1012
#define IDC_STATIC_INTERLOCK            1012
#define IDC_STATIC_EPI_LAMP             1013
#define IDC_STATIC_USER_MEMORY          1013
#define IDC_STATIC_FIBER_OPEN           1014
#define IDC_BUTTON_FIBER_CMD            1015
#define IDC_BUTTON_EPI_PRESET           1016
#define IDC_STATIC_NOSEPIECE            1017
#define IDC_BUTTON_NOSEPIECE_L          1018
#define IDC_COMBO_NOSEPIECE             1019
#define IDC_BUTTON_NOSEPIECE_R          1020
#define IDC_STATIC_CUBE                 1021
#define IDC_BUTTON_CUBE_L               1022
#define IDC_COMBO_CUBE                  1023
#define IDC_BUTTON_CUBE_R               1024
#define IDC_SLIDER_EPI_LAMP             1025
#define IDC_STATIC_EPI_MIN              1026
#define IDC_STATIC_EPI_VALUE            1027
#define IDC_STATIC_EPI_MAX              1028
#define IDC_BUTTON_EPI_L                1029
#define IDC_BUTTON_EPI_R                1030
#define IDC_EDIT_FIBER                  1031
#define IDC_STATIC_FIBER_UNIT           1032
#define IDC_STATIC_FIBER_ND             1033
#define IDC_COMBO_FIBER                 1034
#define IDC_BUTTON_DIA_LAMP             1035
#define IDC_STATIC_DIA_LAMP             1036
#define IDC_BUTTON_DIA_PRESET           1037
#define IDC_SLIDER_DIA_LAMP             1038
#define IDC_STATIC_DIA_MIN              1039
#define IDC_STATIC_DIA_VALUE            1040
#define IDC_STATIC_DIA_MAX              1041
#define IDC_BUTTON_DIA_L                1042
#define IDC_BUTTON_DIA_R                1043
#define IDC_STATIC_ZDRIVE_RANGE         1044
#define IDC_STATIC_ZDRIVE_ALF           1045
#define IDC_COMBO_ZDRIVE_STEP           1046
#define IDC_BUTTON_ZDRIVE_CHANGE        1047
#define IDC_CHECK_ZDRIVE_ALF            1048
#define IDC_SLIDER_ZDRIVE               1049
#define IDC_STATIC_ZDRIVE_MAX           1050
#define IDC_STATIC_ZDRIVE_MIN           1051
#define IDC_STATIC_ZDRIVE_VALUE         1052
#define IDC_STATIC_APERTURE_MIN         1053
#define IDC_STATIC_ZDRIVE_UPPERLIMIT    1053
#define IDC_STATIC_APERTURE_VALUE       1054
#define IDC_STATIC_ZDRIVE_LABEL_UPPER   1054
#define IDC_STATIC_APERTURE_MAX         1055
#define IDC_STATIC_ZDRIVE_LOWERLIMIT    1055
#define IDC_SLIDER_APERTURE             1056
#define IDC_STATIC_ZDRIVE_LABEL_LOWER   1056
#define IDC_BUTTON_APERTURE_L           1057
#define IDC_BUTTON_APERTURE_R           1058
#define IDC_BUTTON_APERTURE_PRESET      1059
#define IDC_SLIDER_DIC                  1060
#define IDC_BUTTON_DIC_L                1061
#define IDC_BUTTON_DIC_R                1062
#define IDC_BUTTON_DIC_CALIBRATION      1063
#define IDC_BUTTON_DIC_CLEAR            1064
#define IDC_COMBO_DIC                   1065
#define IDC_STATIC_DIC1                 1066
#define IDC_STATIC_DIC2                 1067
#define IDC_STATIC_DIC3                 1068
#define IDC_STATIC_DIC4                 1069
#define IDC_STATIC_DIC5                 1070
#define IDC_STATIC_DIC_VALUE            1071
#define IDC_STATIC_INTERLOCK_MODE       1072
#define IDC_COMBO_INTERLOCK             1073
#define IDC_STATIC_ZDRIVE_STEP          1074
#define IDC_BUTTON_ZDRIVE_U             1075
#define IDC_BUTTON_ZDRIVE_UU            1076
#define IDC_BUTTON_ZDRIVE_D             1077
#define IDC_BUTTON_ZDRIVE_DD            1078
#define IDC_BUTTON_AF                   1079
#define IDC_STATIC_ZDRIVE_CONTINUOUS    1080
#define IDC_BUTTON_SEARCH               1081
#define IDC_BUTTON_STOPSEARCH           1082
#define IDC_COMBO_ZDRIVE_SEARCH         1083
#define IDC_STATIC_ZDRIVE_FOCUS1        1084
#define IDC_STATIC_ZDRIVE_FOCUS2        1085
#define IDC_BUTTON_SET_ZDRIVE_LIMIT     1085
#define IDC_STATIC_NOSEPIECE1           1085
#define IDC_BUTTON_ZDRIVE_MAX           1086
#define IDC_BUTTON_ZDRIVE_MIN           1087
#define IDC_COMBO_ZDRIVE_SPEED          1088
#define IDC_BUTTON_ZDRIVE_ESCAPE        1089
#define IDC_STATIC_NOSEPIECE2           1089
#define IDC_STATIC_LED                  1090
#define IDC_STATIC_NOSEPIECE3           1090
#define IDC_EDIT_RANGE_MIN              1091
#define IDC_STATIC_NOSEPIECE4           1091
#define IDC_BUTTON_READ_MIN             1092
#define IDC_STATIC_NOSEPIECE5           1092
#define IDC_EDIT_RANGE_MAX              1093
#define IDC_LIST_INFO                   1093
#define IDC_BUTTON_NOSEPIECE_MEMORIZE   1093
#define IDC_BUTTON_READ_MAX             1094
#define IDC_STATIC_ZDRIVE_TARGET        1094
#define IDC_BUTTON_NOSEPIECE_CLEAR      1094
#define IDC_COMBO_ZDRIVE_TARGET         1095
#define IDC_BUTTON_ZDRIVE_CLEAR         1096
#define IDC_BUTTON_NOSEPIECE1           1097
#define IDC_BUTTON_NOSEPIECE2           1098
#define IDC_RADIO_NOSEPIECE_ON          1098
#define IDC_BUTTON_NOSEPIECE3           1099
#define IDC_RADIO_NOSEPIECE_OFF         1099
#define IDC_BUTTON_NOSEPIECE4           1100
#define IDC_RADIO_SWITCH_ON             1100
#define IDC_BUTTON_NOSEPIECE5           1101
#define IDC_RADIO_SWITCH_OFF            1101
#define IDC_RADIO_BUZZER_ON             1102
#define IDC_RADIO_BUZZER_OFF            1103
#define IDC_CHECK_NOSEPIECE             1104
#define IDC_STATIC_FRM_USER             1105
#define IDC_BUTTON_USERMEMORY_CURRENT   1106
#define IDC_BUTTON_USERMEMORY_INIT      1107
#define IDC_RADIO_INTERLOCK_OFF         1108
#define IDC_RADIO_INTERLOCK_ON          1109
#define IDC_BUTTON_SEND                 1110
#define IDC_EDIT_COMMAND                1111
#define IDC_EDIT_RECIEVE                1112
#define IDC_STATIC_COMMAND              1113
#define IDC_STATIC_RECIEVE              1114
#define IDC_LIST_DEVICE                 1115
#define IDC_STATIC_FRM_AF_OFFSET        1116
#define IDC_STATIC_FRM_AF_RECIPE        1117
#define IDC_CHECK_AF_OFFSET             1118
#define IDC_COMBO_AF_RECIPE             1119
#define IDC_SLIDER_AF_OFFSET            1120
#define IDC_EDIT_OFFSET                 1121
#define IDC_SPIN_OFFSET                 1122
#define IDC_BUTTON_CHANGE               1123
#define IDC_STATIC_PICT_ORIGIN          1124
#define IDC_LVSETUPCTRL1                1125
#define IDC_STATIC_APP_VERSION          1126
#define IDC_STATIC_CONTROLLER_VERSION   1127
#define IDC_STATIC_CONTROLLER_NAME      1128
#define IDC_STATIC_CHECK_SUM            1129
#define IDC_STATIC_SDK_VERSION          1130
#define ID_SELECT_DEVICE                32771
#define ID_FILE_SELECT_DEVICE           32772
#define ID_FILE_COMMAND                 32773
#define ID_STATUS_NOSEPIESE             32774
#define ID_STATUS_CUBE                  32775
#define ID_STATUS_INTERLOCK             32776
#define ID_STATUS_USER_OBSERVATION      32777
#define ID_STATUS_EPIDIA                32778
#define ID_STATUS_ZDRIVE                32779
#define ID_STATUS_DIC                   32780
#define ID_STATUS_SYSTEM                32781
#define ID_VIEW_STANDARD                32782
#define ID_VIEW_EXPAND                  32783
#define ID_SETTING_INITIALIZE           32784
#define ID_SETTING_INTERLOCK            32785
#define ID_SETTING_OFFSET               32786
#define ID_SETTING_CONTROL              32787
#define ID_SETTING_FOCUS                32788
#define ID_SETTING_SOFTLIMIT            32789
#define ID_DIC_CALIBRATION              32790
#define ID_DIC_CLEAR                    32791
#define ID_SETTING_AF_OFFSET            32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
